### ISSUE TITLE
NPE from CheckSignatureRule.apply

### ISSUE THREAD

**Issue by islandsvinur** [mojohaus/animal-sniffer#20]
The execution of the enforcer plugin failed due to `artifact.getFile` being NULL in [CheckSignatureRule.apply](https://github.com/mojohaus/animal-sniffer/blob/animal-sniffer-parent-1.14/animal-sniffer-enforcer-rule/src/main/java/org/codehaus/mojo/animal_sniffer/enforcer/CheckSignatureRule.java#L335):

```
Caused by: java.lang.NullPointerException
        at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:95)
        at org.codehaus.mojo.animal_sniffer.enforcer.CheckSignatureRule.apply(CheckSignatureRule.java:335)
        at org.codehaus.mojo.animal_sniffer.enforcer.CheckSignatureRule.buildPackageList(CheckSignatureRule.java:282)
        at org.codehaus.mojo.animal_sniffer.enforcer.CheckSignatureRule.execute(CheckSignatureRule.java:178)
        at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:193)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```

It seems that Maven's `Artifact.getFile` can be [NULL in cases when dependencies haven't been completely resolved yet](http://stackoverflow.com/questions/21187180/maven-artifact-getfile-returns-nullin-a-multi-module-project).

Animal Sniffer: 1.14
Maven: 3.3.3

**Comment by geirwr** [comment]
same issue,
using animal sniffer: 1.15
maven:3.5.0
