### ISSUE TITLE
NPE from CheckSignatureMojo.execute

### ISSUE THREAD

**Issue by jglick** [mojohaus/animal-sniffer#24]
I am getting

```
java.lang.NullPointerException
	at org.codehaus.mojo.animal_sniffer.maven.CheckSignatureMojo.execute(CheckSignatureMojo.java:211)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
```

when trying to run Animal Sniffer on a new project, even though (AFAIK) I have no improper APIs being used.

[Here](https://github.com/mojohaus/animal-sniffer/blob/animal-sniffer-parent-1.15/animal-sniffer-maven-plugin/src/main/java/org/codehaus/mojo/animal_sniffer/maven/CheckSignatureMojo.java#L211) is the faulty line of code:

```java
match = findMatchingDependency( signature, project.getDependencyManagement().getDependencies() );
```

Effective POM excerpt:

```xml
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>animal-sniffer-maven-plugin</artifactId>
  <version>1.15</version>
  <executions>
    <execution>
      <id>check</id>
      <goals>
        <goal>check</goal>
      </goals>
      <configuration>
        <signature>
          <groupId>org.codehaus.mojo.signature</groupId>
          <artifactId>java17</artifactId>
        </signature>
      </configuration>
    </execution>
  </executions>
  <configuration>
    <signature>
      <groupId>org.codehaus.mojo.signature</groupId>
      <artifactId>java17</artifactId>
    </signature>
  </configuration>
</plugin>
```

**Comment by jglick** [comment]
Fixing the NPE reveals the real POM error:

    For artifact {org.codehaus.mojo.signature:java17:null:signature}: The version cannot be empty.
