### ISSUE TITLE
Version 1.17 is not compatible with java 8 

### ISSUE THREAD

**Issue by xvik** [mojohaus/animal-sniffer#53]
Version 1.17 is compiled with java 9 (`Build-Jdk: 9.0.4`) which has breaking api changes.

I faced problem [here](https://github.com/mojohaus/animal-sniffer/blob/master/animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureChecker.java#L639) (in context of ant task):
```
Caused by: java.lang.NoSuchMethodError: java.nio.CharBuffer.position(I)Ljava/nio/CharBuffer;
	at org.codehaus.mojo.animal_sniffer.SignatureChecker.toSourceType(SignatureChecker.java:639)
	at org.codehaus.mojo.animal_sniffer.SignatureChecker.toSourceForm(SignatureChecker.java:595)
	at org.codehaus.mojo.animal_sniffer.SignatureChecker$CheckingVisitor.error(SignatureChecker.java:565)
	at org.codehaus.mojo.animal_sniffer.SignatureChecker$CheckingVisitor.access$800(SignatureChecker.java:282)
	at org.codehaus.mojo.animal_sniffer.SignatureChecker$CheckingVisitor$1.check(SignatureChecker.java:463)
	at org.codehaus.mojo.animal_sniffer.SignatureChecker$CheckingVisitor$1.visitMethodInsn(SignatureChecker.java:398)
	at org.codehaus.mojo.animal_sniffer.asm.shaded.ClassReader.readCode(ClassReader.java:2211)
	at org.codehaus.mojo.animal_sniffer.asm.shaded.ClassReader.readMethod(ClassReader.java:1274)
	at org.codehaus.mojo.animal_sniffer.asm.shaded.ClassReader.accept(ClassReader.java:679)
	at org.codehaus.mojo.animal_sniffer.asm.shaded.ClassReader.accept(ClassReader.java:391)
	at org.codehaus.mojo.animal_sniffer.SignatureChecker.process(SignatureChecker.java:197)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processClassFile(ClassFileVisitor.java:198)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:116)
	at org.codehaus.mojo.animal_sniffer.ant.CheckSignatureTask.execute(CheckSignatureTask.java:210)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	... 59 more
```

In java 8 `.position(int)` method was in [Buffer](https://docs.oracle.com/javase/8/docs/api/java/nio/Buffer.html#position-int-), but in java 9 new method was added directly to [CharBuffer](https://docs.oracle.com/javase/9/docs/api/java/nio/CharBuffer.html#position-int-)

If 1.17 is supposed to be used only with java 9 (or above) please mention it somewhere. For now, It looks like it was supposed to be working [on 1.7 and above](https://github.com/mojohaus/animal-sniffer/blob/master/pom.xml#L98)

Possible fixes:
* `((Buffer)type).position( i + 1 )` (workaround, could break in other places)
* `--release 7` [compiler flag](http://openjdk.java.net/jeps/247). This way compatibility should be granted.

**Comment by torakiki** [comment]
This is something probably related to MANIMALSNIFFER-49 too. It currently LOG.info this case but running the code with a jdk8 leads to a `java.lang.NoSuchMethodError` like in this case or in [our case](https://bugs.launchpad.net/ubuntu/+source/pdfsam/+bug/1781130)

**Comment by olamy** [comment]
fixed by #cbbd006f6896907f9621d30ae5a80d50d37474e0

**Comment by mithuns** [comment]
I see this has been merged but can you also release this ?
Thanks

**Comment by kaijMueller** [comment]
I could also need this fix. Is there any plan to release 1.18?
