### ISSUE TITLE
failed to process jar: Bad class file

### ISSUE THREAD

**Issue by yschimke** [mojohaus/animal-sniffer#70]
Seen on this PR

https://github.com/square/okhttp/pull/5525

```
$ ./gradlew :okhttp:animalsnifferMain --stacktrace
...
Caused by: java.io.IOException:  failed to process jar /Users/yuri/.gradle/caches/modules-2/files-2.1/org.robolectric/android-all/Q-robolectric-5415296/675f28b006b4836563afee8d2f8468fece4d5bd7/android-all-Q-robolectric-5415296.jar : Bad class file /Users/yuri/.gradle/caches/modules-2/files-2.1/org.robolectric/android-all/Q-robolectric-5415296/675f28b006b4836563afee8d2f8468fece4d5bd7/android-all-Q-robolectric-5415296.jar:libcore/io/Os.class
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processJarFile(ClassFileVisitor.java:185)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:120)
	at org.codehaus.mojo.animal_sniffer.ant.CheckSignatureTask.apply(CheckSignatureTask.java:272)
	at org.codehaus.mojo.animal_sniffer.ant.CheckSignatureTask.buildPackageList(CheckSignatureTask.java:246)
	at org.codehaus.mojo.animal_sniffer.ant.CheckSignatureTask.execute(CheckSignatureTask.java:166)
	... 119 more
Caused by: java.io.IOException: Bad class file /Users/yuri/.gradle/caches/modules-2/files-2.1/org.robolectric/android-all/Q-robolectric-5415296/675f28b006b4836563afee8d2f8468fece4d5bd7/android-all-Q-robolectric-5415296.jar:libcore/io/Os.class
	at org.codehaus.mojo.animal_sniffer.ClassListBuilder.process(ClassListBuilder.java:91)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processJarFile(ClassFileVisitor.java:175)
	... 123 more
Caused by: java.lang.IllegalArgumentException
	at org.codehaus.mojo.animal_sniffer.asm.shaded.ClassReader.<init>(Unknown Source)
	at org.codehaus.mojo.animal_sniffer.asm.shaded.ClassReader.<init>(Unknown Source)
	at org.codehaus.mojo.animal_sniffer.asm.shaded.ClassReader.<init>(Unknown Source)
	at org.codehaus.mojo.animal_sniffer.ClassListBuilder.process(ClassListBuilder.java:69)
	... 124 more
```

**Comment by yschimke** [comment]
Happened after upgrading the robolectric jar from Android P to Q.  But seems like an issue to report here.

**Comment by yschimke** [comment]
Happens with 1.17 and 1.18

**Comment by yschimke** [comment]
This seems fixed in latest version.
