### ISSUE TITLE
NPE from SignatureChecker$CheckingVisitor.find

### ISSUE THREAD

**Issue by jglick** [mojohaus/animal-sniffer#8]
1.14 throws this error on my code:

```
java.lang.NullPointerException
	at org.codehaus.mojo.animal_sniffer.SignatureChecker$CheckingVisitor.find(SignatureChecker.java:502)
	at org.codehaus.mojo.animal_sniffer.SignatureChecker$CheckingVisitor.access$900(SignatureChecker.java:280)
	at org.codehaus.mojo.animal_sniffer.SignatureChecker$CheckingVisitor$1.check(SignatureChecker.java:416)
	at org.codehaus.mojo.animal_sniffer.SignatureChecker$CheckingVisitor$1.visitMethodInsn(SignatureChecker.java:377)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.codehaus.mojo.animal_sniffer.SignatureChecker.process(SignatureChecker.java:195)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processClassFile(ClassFileVisitor.java:176)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:101)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:81)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processDirectory(ClassFileVisitor.java:119)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:97)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:81)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processDirectory(ClassFileVisitor.java:119)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:97)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:81)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processDirectory(ClassFileVisitor.java:119)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:97)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:81)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processDirectory(ClassFileVisitor.java:119)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:97)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:81)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processDirectory(ClassFileVisitor.java:119)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:97)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:81)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processDirectory(ClassFileVisitor.java:119)
	at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:97)
	at org.codehaus.mojo.animal_sniffer.maven.CheckSignatureMojo.execute(CheckSignatureMojo.java:238)
```

[Here](https://github.com/mojohaus/animal-sniffer/blob/animal-sniffer-parent-1.14/animal-sniffer/src/main/java/org/codehaus/mojo/animal_sniffer/SignatureChecker.java#L502) it seems `returnClass` is null.

Presumably introduced by 7349c840a5632cb46cef5e87b3de59e6df06ff78 (MANIMALSNIFFER-49 by @rfscholte). 1.13 works.

**Comment by aclemons** [comment]
I also just ran into this issue. Here is a tiny project to reproduce:
https://github.com/aclemons/animal-sniffer-npe

**Comment by karianna** [comment]
Also ran across this NPE

**Comment by sleicht** [comment]
I don't know if its a new issue but with the project https://github.com/aclemons/animal-sniffer-npe the NPE is solved but a new issue comes up: `animal-sniffer-npe/src/main/java/nz/caffe/sniffer/NullPointerAnimalSniffer.java:30: Undefined reference: java.util.concurrent.ConcurrentHashMap.KeySetView java.util.concurrent.ConcurrentHashMap.keySet()`

**Comment by karianna** [comment]
@sleicht Can you open up a new issue for this one?

**Comment by sleicht** [comment]
Done: #12
