### ISSUE TITLE
Crash when animal sniffer encounters a invalid file with a .jar extension

### ISSUE THREAD

**Issue by ragunathjawahar** [mojohaus/animal-sniffer#82]
```
Caused by: java.io.IOException:  failed to process jar /home/rj/../resources/test/jar-test-artifacts/not-a-jar.jar : zip END header not found
        at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processJarFile(ClassFileVisitor.java:185)
        at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.process(ClassFileVisitor.java:120)
        at org.codehaus.mojo.animal_sniffer.ant.CheckSignatureTask.apply(CheckSignatureTask.java:259)
        at org.codehaus.mojo.animal_sniffer.ant.CheckSignatureTask.buildPackageList(CheckSignatureTask.java:246)
        at org.codehaus.mojo.animal_sniffer.ant.CheckSignatureTask.execute(CheckSignatureTask.java:166)
        ... 124 more
Caused by: java.util.zip.ZipException: zip END header not found
        at org.codehaus.mojo.animal_sniffer.ClassFileVisitor.processJarFile(ClassFileVisitor.java:142)
        ... 128 more
```

I have a file in my project, that is not actually a jar. When Animal Sniffer encounters this file, it crashes with an exception.

**Comment by ragunathjawahar** [comment]
Folks, I am checking in to see if you are still accepting PRs before I work on this. Thank you.

**Comment by ragunathjawahar** [comment]
Ended up renaming the file to the actual extension.
